### ISSUE TITLE
Describe .pywren_config in "getting started"

### ISSUE THREAD

**Issue by kgjamieson** [pywren/pywren#134]
It appears that at least these things need to be defined:

    AWS_REGION = config['account']['aws_region']
    FUNCTION_NAME = config['lambda']['function_name']
    S3_BUCKET = config['s3']['bucket']
    S3_PREFIX = config['s3']['pywren_prefix']
    RUNTIME_S3_BUCKET = config['runtime']['s3_bucket']
    RUNTIME_S3_KEY = config['runtime']['s3_key']

An example would be very helpful.
In particular, can config['s3']['bucket'] and config['runtime']['s3_bucket'] be the same? 

Presumably config['lambda']['function_name'] is the relative path to the main .py file

**Comment by shivaram** [comment]
@kgjamieson did you try out the `pywren-setup` script ? That should create the config file for you

**Comment by kgjamieson** [comment]
Gah. Sorry, I thought that was interactive install and dismissed it. Thanks
