### ISSUE TITLE
lapack/blas calls very slow on multicore machines for stand alone mode

### ISSUE THREAD

**Issue by Vaishaal** [pywren/pywren#137]
Consider the following python script
```
import scipy.linalg
import numpy as np
import time
x = np.random.randn(4096, 4096)
x = x.dot(x.T)
y = np.random.randn(4096, 1000)
t = time.time()
scipy.linalg.solve(x,y, sym_pos=True)
e = time.time()
print("Took {0}".format(e - t))`
```

The default runtimes take > 135 seconds to execute the above code. Whereas a standard anaconda install takes ~2 seconds to execute the above code. This was observed on a c3.8xlarge which has 16 hardware cores.

**Comment by ericmjonas** [comment]
@Vaishaal Determined this was due to `OMP_NUM_THREADS` being set to 1 in wrenhander. we do this because lambdas run on containers whose reports of available cores confuse MKL. We should move the setting of this env into the lambda-specific part of the wrenhandler
