### ISSUE TITLE
standalone non-deterministically drops jobs when > 50 instances are spun up

### ISSUE THREAD

**Issue by Vaishaal** [pywren/pywren#197]
https://github.com/pywren/pywren/blob/master/pywren/scripts/standalone.py#L229-L243

Throws an exception when there are a lot of instances (from my experiments > 50 suffices to trigger the bug), because the default EC2 Log Group creation limit is super low (AFAIK almost all the default cloudwatch limits are very low). Since this happens outside a try: except, the manager process just assumes everything was handled successfully and deletes the message from the SQS queue, leading to much frustration.

We could jitter in the job handler, but I'm worried that will make our per job latency even higher since now this has to happen for every job...

Currently I'm commenting this logging code out because personally these logs have never helped me. But what should we do about this issue?

**Comment by ericmjonas** [comment]
Sorry is this log stream or log group limits ? And why would jittering the
log stream creation hurt per job latency ? Log streams are per machien not
per job, right ?

**Comment by ericmjonas** [comment]
@Vaishaal can you get on the eric-fix-standalone branch and see if you still have this problem? It switches from processes to threads and thus only creates one instance of the CloudWatchLogHandler; you might still need to jitter the start-up a bit to prevent the service from being hammered, but in this case explicitly it shouldn't be a problem.

**Comment by ericmjonas** [comment]
I believe this is fixed in branch `eric-fix-standalone`
