### ISSUE TITLE
Multiple Executors on single standalone instance

### ISSUE THREAD

**Issue by Vaishaal** [pywren/pywren#216]
Long standing feature request.

We should be able to invoke standalone instances with multiple workers inside a single node. 
This will allow users to automagically to leverage parallelism in multicore machines.

I'm imaging something like this:

```
 pywren standalone launch_instances 1 --parallelism 8
```

**Comment by apengwin** [comment]
The audio was cutting out throughout the meeting, but I don't think I got why why do launch and terminate via command line and not in python?

**Comment by Vaishaal** [comment]
@ericmjonas doesn't want to support it because he thinks its bad behavior.

**Comment by apengwin** [comment]
Gotcha. Also I think this is a duplicate of #153

**Comment by ericmjonas** [comment]
To be clear, I think that we have to manage expectations correctly here.
Remember serverless is our primary use case. There's all sorts of
complexity that happens when we start launching these things in actual code
paths that we need to think about.

**Comment by shivaram** [comment]
+1 to what @ericmjonas said

**Comment by Vaishaal** [comment]
I do think the min_executors thing he mentioned was the way to go.

**Comment by Vaishaal** [comment]
This was handled by  #224
