### ISSUE TITLE
Add license headers to all files

### ISSUE THREAD

**Issue by Vaishaal** [pywren/pywren#234]

**Comment by gilv** [comment]
@ericmjonas @Vaishaal any progress with this? thanks

**Comment by ericmjonas** [comment]
@ooq can you create the branch and a PR for this?

**Comment by ooq** [comment]
@ericmjonas sure, I can do that.

**Comment by apengwin** [comment]
I think this was addresed in #238

**Comment by ooq** [comment]
@apengwin Right. Closing this issue.
