### ISSUE TITLE
pywren-setup ends with no module named pywren

### ISSUE THREAD

**Issue by suhasghorp** [pywren/pywren#242]
Trying pywren for the first time, anaconda python 3.6.3 on windows. Getting "no module named pywren" in pywren-setup. here is the complete log:
C:\Users\suhasghorp>pywren-setup
This is the PyWren interactive setup script
Your AWS configuration appears to be set up, and your account ID is 73xxxxxxxx
This interactive script will set up your initial PyWren configuration.
If this is the first time you are using PyWren then accepting the defaults should be fine.
What is your default aws region? [us-west-2]:
Location for config file:  [C:\Users\suhasghorp/.pywren_config]:
C:\Users\suhasghorp/.pywren_config already exists, would you like to overwrite? [y/N]: y
PyWren requires an s3 bucket to store intermediate data. What s3 bucket would you like to use? [suhasghorp-pywren-73]:
Bucket does not currently exist, would you like to create it? [Y/n]: y
PyWren prefixes every object it puts in S3 with a particular prefix.
PyWren s3 prefix:  [pywren.jobs]:
Would you like to configure advanced PyWren properties? [y/N]: n
PyWren standalone mode uses dedicated AWS instances to run PyWren tasks. This is more flexible, but more expensive with fewer simultaneous workers.
Would you like to enable PyWren standalone mode? [y/N]: n
Creating config C:\Users\suhasghorp/.pywren_config
new default file created in C:\Users\suhasghorp/.pywren_config
lambda role is pywren_exec_role_1
Creating bucket suhasghorp-pywren-73.
Creating role.
Deploying lambda.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Successfully created function.
Pausing for 10 sec for changes to propagate.
Traceback (most recent call last):
  File "c:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\anaconda\Scripts\pywren-setup.exe\__main__.py", line 9, in <module>
  File "c:\anaconda\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\anaconda\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\anaconda\lib\site-packages\pywren\scripts\setupscript.py", line 215, in interactive_setup
    ctx.invoke(pywrencli.test_function)
  File "c:\anaconda\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\anaconda\lib\site-packages\pywren\scripts\pywrencli.py", line 379, in test_function
    res = fut.result(storage_handler=wrenexec.storage)
  File "c:\anaconda\lib\site-packages\pywren\future.py", line 202, in result
    reraise(*self._traceback)
  File "c:\anaconda\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/var/task/jobrunner.py", line 29, in <module>
ModuleNotFoundError: No module named 'pywren'

**Comment by Vaishaal** [comment]
Hello. 

If you launch python
and do 
`import pywren`

does it work?

**Comment by manu2000** [comment]
I see the same error, when I test pywren: 
`pywren test_function`

> pywren test_function
> Traceback (most recent call last):
>   File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Anaconda3\Scripts\pywren.exe\__main__.py", line 9, in <module>
>   File "c:\anaconda3\lib\site-packages\pywren\scripts\pywrencli.py", line 581, in main
>     return cli() # pylint: disable=no-value-for-parameter
>   File "c:\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\anaconda3\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\anaconda3\lib\site-packages\click\decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\anaconda3\lib\site-packages\pywren\scripts\pywrencli.py", line 379, in test_function
>     res = fut.result(storage_handler=wrenexec.storage)
>   File "c:\anaconda3\lib\site-packages\pywren\future.py", line 202, in result
>     reraise(*self._traceback)
>   File "c:\anaconda3\lib\site-packages\six.py", line 692, in reraise
>     raise value.with_traceback(tb)
>   File "/var/task/jobrunner.py", line 29, in <module>
> ModuleNotFoundError: No module named 'pywren'

I am able to succesfully import pywren in anaconda. I am using a windows machine.
