### ISSUE TITLE
pywren not functioning as expected on windows develepment env

### ISSUE THREAD

**Issue by Leila-karimi** [pywren/pywren#243]
Hi there,
Does anyone have experience with pywren on windows env?
Is there any way I could get passed the following errors/issues when I run the test_function/any pywren functions?
The S3 bucket and lambda functions exist already. I just have installed pywren and tried test_function and hit this error!

> ImportError: No module named pywren.serialize.cloudpickle.cloudpickle

In the S3 bucket I've got output files created with  pywren_prefix included in the filename. It is not creating folders! with my  pywren_prefix!

![image](https://user-images.githubusercontent.com/20510368/40455688-759df0a4-5f31-11e8-832b-db139dd0a9ef.png)

Also, I noticed pwd  is not recognised in my setup script. Which I believe can be issue if used in any other pywren main scripts.

Thanks in advance

**Comment by Vaishaal** [comment]
Hello,

What version of python are you using on Windows. Are you using anaconda?

Also could you clarify your S3 question. Amazon S3 only supports key, value pairs. There is no concept of "folders". So the behavior you are describing is expected.

**Comment by Leila-karimi** [comment]
I am using python:2.7.14 and no I am not using anaconda.
About S3 question, I have these two settings in my pywren_config file:

> 
> s3:
>     bucket: leila.pywren.bucket
>     pywren_prefix: leila.pywren.jobs

If I run test_function from a mac machine with my config file, a folder would be created as shown below, But if I run it from windows the files with the prefix in the name would be created!

![image](https://user-images.githubusercontent.com/20510368/40517275-c60ef198-5ff7-11e8-9bdf-95a3fd9b9ba0.png)

**Comment by apengwin** [comment]
@Leila-karimi  I think that has to do with path delimiters. / on Macs and Linux, vs \ on windows

**Comment by Leila-karimi** [comment]
@apengwin Yes, you're right. I agree. Is there any chance we could get a fix?!
Also, Do you have any idea about the error I hit:

> ImportError: No module named pywren.serialize.cloudpickle.cloudpickle

**Comment by Vaishaal** [comment]
Do you get the import error both on mac and windows?

**Comment by Leila-karimi** [comment]
@Vaishaal it's happening just on windows:|

**Comment by Vaishaal** [comment]
hmmm.

First can you open an interpreter in Windows and run:
`import  pywren.serialize.cloudpickle.cloudpickle `
Let me know if the above line fails.

Then can you try this on an anaconda install of python if possible?

**Comment by Leila-karimi** [comment]
@Vaishaal  Interesting! The import didn't fail.
And I just worked it out using docker! I'll update on your second questions when I got the chance to install anaconda.
Thanks for your replies anyways.

**Comment by leilakarimi** [comment]
@Vaishaal FYI I still get the same error with anaconda:

> (base) D:\testPywren>pywren test_function
> Traceback (most recent call last):
>   File "c:\programdata\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
>   "__main__", fname, loader, pkg_name)
>   File "c:\programdata\anaconda2\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\ProgramData\Anaconda2\Scripts\pywren.exe\__main__.py", line 9, in <mo
> dule>
>   File "c:\programdata\anaconda2\lib\site-packages\pywren\scripts\pywrencli.py",
>  line 581, in main
>     return cli() # pylint: disable=no-value-for-parameter
>   File "c:\programdata\anaconda2\lib\site-packages\click\core.py", line 722, in
> __call__
>     return self.main(*args, **kwargs)
>   File "c:\programdata\anaconda2\lib\site-packages\click\core.py", line 697, in
> main
>     rv = self.invoke(ctx)
>   File "c:\programdata\anaconda2\lib\site-packages\click\core.py", line 1066, in
>  invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\programdata\anaconda2\lib\site-packages\click\core.py", line 895, in
> invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\programdata\anaconda2\lib\site-packages\click\core.py", line 535, in
> invoke
>     return callback(*args, **kwargs)
>   File "c:\programdata\anaconda2\lib\site-packages\click\decorators.py", line 17
> , in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\programdata\anaconda2\lib\site-packages\pywren\scripts\pywrencli.py",
>  line 379, in test_function
>     res = fut.result(storage_handler=wrenexec.storage)
>   File "c:\programdata\anaconda2\lib\site-packages\pywren\future.py", line 202,
> in result
>     reraise(*self._traceback)
>   File "/var/task/jobrunner.py", line 29, in <module>
> ImportError: No module named pywren.serialize.cloudpickle.cloudpickle

**Comment by zehric** [comment]
This issue should be fixed after #279 was merged. Closing. Please reopen if this issue comes up again.
