### ISSUE TITLE
Guide needed: How to use' extra_meta ' parameter in pywren executor?

### ISSUE THREAD

**Issue by vijayaratha** [pywren/pywren#244]
Sorry, I do not see any forum or stackoverflow tag to raise a guide information. So using this to get some guide/to update existing your documentation.

Im new to python/pywren library. I try to use pywren default executor to achieve parallel processing[1]
My function expects more than one input ( a list of iterable inputs and some other parameter)
eg: 

> def addone(x ,clientId):
>     return x + 1
> 
> xlist = np.arange(10)
> Executor.map(addone, xlist)
> 

in this case how can I use Executor.map function?

> Executor.map(addone,xlist)//<---How to pass **clientid** parameter here?

Can i use ' extra_meta ' attribute? If so, can you point me an example?

[1]http://pywren.io/docs/

**Comment by Vaishaal** [comment]
Hi!

So the easiest way to get pywren to use more than one argument is to ``curry" the fixed arguments using an another function. So in your example it would be something like the following:

```
Executor = pywren.default_executor()
def addone(x ,clientId):
return x + 1

xlist = np.arange(10)
Executor.map(lambda x: addone(x, client_id), xlist)
```

**Comment by vijayaratha** [comment]
That's great..but one more, here what is 'lambda X' in your solution?

**Comment by Vaishaal** [comment]
sorry the extra_meta parameter is an extra parameter we use internally for diagnostics its not meant to be exposed to the user!

**Comment by vijayaratha** [comment]
Thanks..Few more 

- What  is the difference between **Executor.map() and Executor.call_async()** ?

- Can pywren handle in memory parallel processing and will return result as expected? (That is, if my function uses some in memory calculations , can that be handled parallel?)

**Comment by Vaishaal** [comment]
Executor.call_async(f, 1) is equivalent to  Executor.map(f, [1]) (if that mkaes sense)

If your python uses multiple threads/processes it should work fine as  long as all the data for the function is serialized and sent to the remote executor

**Comment by vijayaratha** [comment]
Thank you..
