### ISSUE TITLE
Pywren and Amazon RDS issue

### ISSUE THREAD

**Issue by vijayaratha** [pywren/pywren#248]
I have tried few use cases with my test case +raw sql/python ORM support

- I have tried an example with python ORM (SQLAlchemy module) with pywren  executor library, but it didn't work as expected (simple select call). Is this working or not (Does pywren library support python ORM)?

- I have tried native sql with pyren executor, without iterating list, it is working as expected.
eg:

> getSite() :
>     sql = text('select siteid from atgsitetopoll')     
>      result = db.engine.execute(sql)
>      names = []
>      for row in result:
>         names.append(row[0])
>      print names
>Save to DB() ..further process. Data saved -Works

> pywrenexecutor = pywren.default_executor()
> pywrenexecutor.map(getSite(), [])

- I have tried native sql with pyren executor, with iterating list, it is not working .

eg:

> getSite(siteId) :
>     sql = text( """select tankId from atgsitetopoll where siteid= """ + str(siteId) + """)     
>      result = db.engine.execute(sql)
>     Save to DB() ..further process. Nothing saved

> pywrenexecutor = pywren.default_executor()
> pywrenexecutor.map(getSite, siteList)

What I'm doing wrong here?

**Comment by Vaishaal** [comment]
Are you getting an exception? What is the exact failure mode? 
Is SQLAlchemy built in to python or is it a package you have to install separately.

**Comment by vijayaratha** [comment]
Hi Vaishaal;
I avoided sqlalchemy module for the timebeing..
My simple test purpose is pwren can  access the AWS RDS and do select query.
Here is my sample test code

> import pymysql.cursors
> import pywren
> 
> def getIps(site) :
>     ipList = []
>     cnx = pymysql.connect(host='xx.us-east-2.rds.amazonaws.com', user='xx',
>                           password='xx', database='xx', autocommit=True,read_timeout=1000, connect_timeout=300)
>     cursor = cnx.cursor()
>     query = "SELECT  ipaddress FROM atgsitetopoll where siteid =  """ + site + """"""
>   ```
>   cursor.execute(query)
>     for (ipaddress) in cursor:
>         ipList.append(ipaddress)
>     cursor.close()
>     cnx.close()
>     return ipList
> 
> siteList=[]
> cnx = pymysql.connect(host='xxxx.us-east-2.rds.amazonaws.com', user='xx',
>                           password='xx', database='xx', autocommit=True)
> cursor = cnx.cursor()


> query = "SELECT clientid, siteid, ipaddress, port FROM atgsitetopoll"
> cursor.execute(query)
> for (clientid, siteid, ipaddress, port) in cursor:
>     siteList.append(siteid)
> cursor.close()
> cnx.close()
> print siteList
> 
> wrenexec = pywren.default_executor()
> futures = wrenexec.map(getIps, siteList)
> 
> print [f.result() for f in futures]

I can print siteList (means before calling pywren executor, I can query RDS) But after calling getIps via executor I get timed out error;

> pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxx.us-east-2.rds.amazonaws.com' ([Errno 110] Connection timed out)")

p.s: both pywren lambda and RDS are in same us-east-2 region

**Comment by vijayaratha** [comment]
It was pywren role permission issue. After updating role permission it works.
