### ISSUE TITLE
Question about map result and wait function

### ISSUE THREAD

**Issue by leilakarimi** [pywren/pywren#250]
Hi there,

I am trying to read 1000 tiny xml files and convert and merge them into 1 csv file.
The final csv file has a size of 180 KB. (quite small)
The time taken with the following code is around 25 minutes.

`
    t1 = time.time()
    wrenexec = pywren.default_executor()
    uploadController = UploadController(BUCKET_NAME, AWS_REGION, Destination)
    
    # read from s3 xml objects and convert and return csv gz stream
    futures = wrenexec.map(uploadController.read,  [key for key in keys if key.endswith('.xml')])

    dones = [f.result() for f in futures]

    # write multiple streams to 1 gz file
    uploadController.writeMultipleStreams(dones)
    t2 = time.time()
    run_statuses = [f.run_status for f in futures]

    print run_statuses
    #print("results:{0}".format(run_statuses))
    print("runtime:{:3.0f}".format(t2 - t1))
`

But, with wait function as below it takes about 85 seconds.
`

    t1 = time.time()

    wrenexec = pywren.default_executor()
    pywren.log_level = pywren.wren.logging.INFO

    uploadController = UploadController(BUCKET_NAME, AWS_REGION, Destination)

    read_futures = wrenexec.map(uploadController.read, keys)

    dones, ndones = pywren.wait(read_futures)

    #print [c.callset_id for c in dones]

    res = uploadController.writeMultipleStreams([c.result() for c in dones])

    # results = [f.result() for f in futures]
    # res = {'results': results}
    t2 = time.time()

    print("results:{0}".format(res))
    print("runtime:{:3.0f}".format(t2 - t1))
`
I expected the first one be quicker than the wait function as I presumed it with async call it should be as completed returns! whereas the wait function waits until all completed and then returns!

I am a bit confused here. I appreciate if anyone can explain whats happening with each scenario?

**Comment by Vaishaal** [comment]
Hi.

So the problem here is that when you do pywren.wait(...) multiple threads are used to fetch the results from S3, where as  [f.result() for f in futures] will download the results in a single thread.  

If you want to do something asynchronously I would use pywren.wait(futures, return_when=pywren.wait.ANY_COMPLETED).

**Comment by leilakarimi** [comment]
@Vaishaal Awesome! totally makes sense now!
Thanks heaps:)
