### ISSUE TITLE
eu-west-1 runtime bucket not existing / not public

### ISSUE THREAD

**Issue by rwinzinger** [pywren/pywren#252]
Hi there,

I tried to install pywren in eu-west-1 one but the setup fails with

```
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/pywren/storage/s3_backend.py", line 35, in get_object
    r = self.s3client.get_object(Bucket=self.s3_bucket, Key=key)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist

```
The config file shows that the runtimes are expected in a bucket in eu-west-1:

```
runtime:
    s3_bucket: pywren-public-eu-west-1
    s3_key: pywren.runtimes/default_3.6.meta.json

```
But also an ls on this bucket would not work:

```
[ec2-user@ip-10-0-0-247 ~]$ aws s3 ls s3://pywren-public-eu-west-1

An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
```

**Comment by ericmjonas** [comment]
Hi so it looks like we never actually deployed the runtimes to the eu-west-1 bucket! I'm creating them now and should be deploying them today.

**Comment by ericmjonas** [comment]
Ok we've run into some hiccups on runtime creation (conda changed a few annoying things), for the meantime we're testing a fix that will by default if you're running in an unsupported region use the runtimes from the us-west-2 region. All your own code and data and state will still live in your home region/bucket, just the python runtime will be downloaded from afar. It's suboptimal but a quick fix and I think you guys are on a deadline? Let me know if this would work.
