### ISSUE TITLE
No module named 'pwd'

### ISSUE THREAD

**Issue by manu2000** [pywren/pywren#259]
When I try to setup pywren using "pywren-setup" I get the following error:

```
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\pywren-setup.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\lib\site-packages\pywren\scripts\setupscript.py", line 2, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

I am using a windows machine and when I googled this error I found that the package 'pwd' does not exist for windows. Is there a workaround for this?

**Comment by manu2000** [comment]
pywren/pywren/scripts/setupscript.py imports pwd which is not available in windows. There is a function in that file to get username:

```
def get_username():
    return pwd.getpwuid(os.getuid())[0]
```
 
If this is changed to:

```
def get_username():
    
    try:
        import pwd
    except ImportError:
       pwd = None
       import getpass
       
    if pwd:
        userName = pwd.getpwuid(os.getuid())[0]
    else:
        userName = getpass.getuser()
    
    return userName
```
the error should disappear.

Credit to ericLemanissier for suggesting this here: [https://github.com/b-ryan/powerline-shell/issues/323]

**Comment by Vaishaal** [comment]
Hey Manu,

Yeah sorry the pwd module doesn't exist for windows. That workaround works though. Could you make a pull request with that fix, we'll gladly merge it in.
