### ISSUE TITLE
Python 3.7 runtime

### ISSUE THREAD

**Issue by semitom** [pywren/pywren#267]
Python 3.7 has been released on June 27th: https://www.python.org/downloads/release/python-370/

Pywren does not currently have a runtime for python 3.7:

```bash
> pywren create_config
No matching runtime package for python version  3.7
Python 2.7 runtime will be used for remote.
```

**Comment by Vaishaal** [comment]
Ok we are on this.

**Comment by Vaishaal** [comment]
We have added a 3.7 runtime to the default regions.

**Comment by Vaishaal** [comment]
There are some major caveats with this runtime. 

* The minimum scipy version for py37 is 'scipy==1.1.0' (the old runtimes had 0.19.1) which unfortunately brings a lot of detritus (large shared objects). Even with a modified shrinkconda that aggressively removes sos. The runtime cannot be squeezed into the 512 MB disk space limitation. To remedy this the default runtime here *does not* include scipy. @shivaram @ericmjonas  any comments/ideas?

**Comment by shivaram** [comment]
Could you provide a breakdown on how the size increases after shrinkconda has run with scipy 1.1.0 ? Is it close to 512MB or is it much bigger ? And if I'm right, we currently have no runtime for 3.7 right ? I'm trying to understand if this is a regression or a new but limited feature

**Comment by Vaishaal** [comment]
No runtime for 3.7. So this a new but limited feature.

* Currently its 551 MB. 
Output of ``du -h --max-depth=3  | sort -h | tail -n30`` for python3.6 vs python3.7 in /tmp/condaruntime

3.7:
```
620K    ./share/info
660K    ./lib/python3.7/pydoc_data
836K    ./include/python3.7m
908K    ./lib/tk8.6/demos
912K    ./share/man/man1
1000K   ./lib/python3.7/lib2to3
1.1M    ./lib/sqlite3.21.0
1.6M    ./include/openssl
1.6M    ./lib/tcl8.6/encoding
1.7M    ./lib/python3.7/idlelib
1.8M    ./lib/python3.7/encodings
1.9M    ./lib/python3.7/ensurepip
1.9M    ./lib/python3.7/__pycache__
1.9M    ./lib/tk8.6
2.4M    ./compiler_compat
2.4M    ./lib/tcl8.6
3.3M    ./lib/python3.7/distutils
4.4M    ./share/doc/openssl
4.7M    ./share/doc
4.9M    ./include
5.0M    ./share/man/man3
5.3M    ./conda-meta
5.4M    ./lib/python3.7/lib-dynload
6.2M    ./share/man
12M     ./share
16M     ./bin
143M    ./lib/python3.7/site-packages
170M    ./lib/python3.7
472M    ./lib
511M    .
```

3.6:

```
376K    ./ssl
380K    ./lib/python3.6/tkinter
436K    ./lib/python3.6/asyncio
492K    ./lib/python3.6/xml
512K    ./lib/tcl8.5/msgs
620K    ./lib/python3.6/email
636K    ./lib/python3.6/pydoc_data
748K    ./conda-meta
804K    ./include/python3.6m
840K    ./lib/tk8.5/demos
988K    ./lib/python3.6/lib2to3
1.2M    ./include/freetype2
1.4M    ./lib/python3.6/idlelib
1.6M    ./lib/tcl8.5/encoding
1.6M    ./share/doc
1.6M    ./share/doc/tiff-4.0.6
1.8M    ./lib/python3.6/encodings
1.8M    ./lib/tk8.5
1.9M    ./include/openssl
1.9M    ./lib/python3.6/__pycache__
2.0M    ./share
2.5M    ./lib/tcl8.5
3.3M    ./lib/python3.6/distutils
4.5M    ./lib/python3.6/lib-dynload
5.3M    ./bin
5.7M    ./include
169M    ./lib/python3.6/site-packages
192M    ./lib/python3.6
386M    ./lib
400M    .
```

**Comment by Vaishaal** [comment]
I am not going to muck with the sos that the newer versions of numpy need. I think documenting this is the correct thing to do. If our runtime plans for 0.5 pan out this should be a non-issue in by v0.5.

**Comment by ooq** [comment]
I think the 3.7 runtime falls into the "new feature with limited capability' category. But it might still be worth discussing if we want to publish it at all given it might cause a regression experience. New users would likely opt for 3.7 as well.

**Comment by Vaishaal** [comment]
do we have any survey of how many of our users use scipy? There was even discussion removing this from the default runtime... 

I still think a working 3.7 runtime without scipy is much better than no 3.7 runtime.

**Comment by shivaram** [comment]
I am not aware of any such surveys. I could be convinced that providing some runtime for 3.7 is better than having no runtime. Is there a way we could warn users if/when they try to use scipy with 3.7 ?

**Comment by Vaishaal** [comment]
That would involve mucking with the serializer and would be very hacky. 
I'd say we just document it in our documentation, and a quick google search will point people here.
We can print a warning during setup?

**Comment by Vaishaal** [comment]
I'm going to close this issue and open a specific issue for adding scipy to 3.7 runtime.
