### ISSUE TITLE
sklearn usage example

### ISSUE THREAD

**Issue by mlisovyi** [pywren/pywren#280]
Hi,

is there an example or a test illustrating how to scale up a sklearn method (e.g. a hyper-parameter optimisation in CV)? I fail to find anything as a guidance for a beginner.

Best regards,
Misha

**Comment by apengwin** [comment]
You can check out
https://github.com/ucbrise/risecamp/blob/risecamp2017/pywren/hyperparameter-optimization.ipynb

**Comment by mlisovyi** [comment]
Thanks for the example
