### ISSUE TITLE
Pywren Runtime buckets not public

### ISSUE THREAD

**Issue by Jimmy89o** [pywren/pywren#305]
It seems that the new pywren-runtime buckets are not publically accessible:

``` 
aws s3 ls pywren-runtimes-public-us-west-1
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```
I have tried a few different regions / buckets but get the same reults.

**Comment by Vaishaal** [comment]
Whoops we didn't enable the list permission (read access was allowed however)

**Comment by Vaishaal** [comment]
Fixing now.

**Comment by Jimmy89o** [comment]
Thanks looks all good now :)
