### ISSUE TITLE
Better synchronization of runtime information with local client

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#44]
Right now, what modules to _not_ upload is hardcoded. We should be able to do better than that, especially due to conda env. This is mostly a placeholder to keep the issue alive.

**Comment by ericmjonas** [comment]
This actually shouldn't be that hard now that we have the runtime metadata and are validating it -- we could effectively replace the calls to preinstalled.

**Comment by shivaram** [comment]
This is part of the serialization cleanup

**Comment by shivaram** [comment]
@ericmjonas Am I right in understanding that you are also addressing this in the `serialization-bugs` branch ?

**Comment by ericmjonas** [comment]
Yes because this requires changing the serialization infrastructure to take
in a more automatically-generated list of preinstalls from the runtime
`meta.json`
