### ISSUE TITLE
`result(throw_except=False)` can still throw out-of-time exceptions

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#71]
We need to fix this handling of exceptions, so that result can be used to poll status for jobs that will fail

**Comment by ooq** [comment]
This is probably that in `if call_status['exception'] is not None:` we didn't check `throw_except`

**Comment by ericmjonas** [comment]
I think you're right -- I'll put in a PR soon once I'm done debugging the setup time bug
