### ISSUE TITLE
Turn on runtime sharding by default

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#75]
1. This should probably be on by default

2. It's not clear if it should really be an argument to the executor or in the config or what.

**Comment by shivaram** [comment]
As a part of this, investigate if we can move the runtime tar.gz to cloudfront and also check if this affects pricing

**Comment by shivaram** [comment]
As @ooq pointed out -- we should move this flag to the config file so that new runtimes / the python code doesn't worry about this decision

**Comment by ericmjonas** [comment]
@shivaram I was thinking that updating the runtime meta information that we put out there, we could just also include a list of URLs for the actual runtime -- basically a mirrors key that contains the path to the ~50 (or however many) actual s3 objects, and just have the client randomly (or round-robin) select each one. That way, the default behavior would be to download the `meta` and then pick from within that list.

**Comment by ooq** [comment]
|workers | no-sharding        | sharding           | cloudfront  | via s3.amazonwas.com |
| :-------------:  | :-------------: |:-------------:| :-------------:| :-------------: |
|100|	12s|	12.9s|	18s	|7s|
|1000|	44s	|18.6s|	101s|	31s|

Some  totally non-scientific numbers for runtime download time you might be interested. @ericmjonas @shivaram 
Done in 1 run. No error bar provided. Totally unfair comparison, given cloudfront is designed to scale with respect to "edges".
Right now S3 sharding gives the best performance.
