### ISSUE TITLE
Handle exception pickling

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#78]
See the comments on PR #47 at the end -- @ooq is still seeing unpickleable exceptions.

**Comment by ericmjonas** [comment]
@ooq We were referencing an exception that you had seen that couldn't be serialized and yet still had a problem -- do you have a testcase perhaps ? I can't find the original problem.

**Comment by ooq** [comment]
@ericmjonas Sorry that I could not recall the exact exception I had.
Just curious, do we have a rough list of 1) what exceptions cannot be pickled? 2) what exceptions can be pickled but cannot be unpickled? 
And, is `Exception` the only object that causes pickle/unpickle issues? Just want to make sure we don't have to stress out about `exc_traceback`. If `exc_traceback` is not the worry, why are we doing `str(exc_traceback)` here?

**Comment by ericmjonas** [comment]
Sometimes `exc_traceback` contains pieces of the exception that cannot be pickled and I wanted to be 100% sure things propagated correctly. I don't have a list, but we have example exceptions that I test in `test_pickle.py` where we create objects (and exceptions) that fail on either pickle or unpickle.
