### ISSUE TITLE
Support 3.4 runtime (and others)

### ISSUE THREAD

**Issue by ooq** [pywren/pywren#95]
We have users with python 3.4. Should we build and upload 3.4 runtime? and other python versions?

**Comment by shivaram** [comment]
Is it the pickling / serialization that is sensitive to even minor version changes in Python ? I think adding 3.4 might be fine as it is probably in the top-3 of versions used (see https://hynek.me/articles/python3-2016 for example), but maintaining more versions does make testing etc. more expensive

**Comment by ericmjonas** [comment]
I think it's easier for most of the users we care about to make them upgrade to 3.x then try and support an additional runtime. Runtime builds already take too long.

**Comment by ericmjonas** [comment]
The other issue here is that we don't want to increase our test runtime by 33%

**Comment by ooq** [comment]
Agree on that testing is one huge concern here.
However, I still don't want to have nightmares of those 3.4 users struggling and suffering.
One potential solution I'm thinking, is that can we:
1, only test 2.6 and 3.6 for development -- this even reduces our current testing time
2, testing all sub-versions for releases

The hope here is that differences between subversion should be small and easy to fix.

**Comment by ericmjonas** [comment]
I'm going to mark this closed given that we now 1. bail on `setup.py` if we have less than 3.4 and 2. have 3.4 runtimes deployed to the new runtime location
