### ISSUE TITLE
When creating the lambda we indiscriminately upload too much

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#98]
PyWren's lambda indiscriminately uploads the entire source dir. If for some reason the user has put crap in there, such as a copy of the runtime, it gets uploaded as well and then the Lambda API errors telling us that the files are too big. It's really confusing. We should check that we are only uploading necessary files.

**Comment by ooq** [comment]
Are you talking about users putting crap in python module folders?

**Comment by ericmjonas** [comment]
Yes, exactly, but it's not that bizarre of a use case: 
1. user clones pywren github
2. user installs via `pip -e`
3.  User adds things to pywren source dir, not thinking about it. Maybe they download a runtime, as happened in this case
4. Our default upload-all policy... uploads everything, confusing them. 

I think the right answer here is a whitelist, which is easy to implement.
